version: '3.7'

x-aliases:
  - &common-options
    network_mode: bridge
    stdin_open: true
    tty: true

networks:
  default:
    name: bridge
    external: true

services:

  # Bash ------------------------------- {{{1
  bash:
    image: bash
    container_name: bash
    labels: [ 'devenv.type=bash' ]
    <<: *common-options

  bash-repl:
    image: bash
    container_name: bash-repl
    labels: [ 'devenv.type=bash-repl' ]
    <<: *common-options

  # Clang ------------------------------ {{{1
  clang:
    image: local/clang
    build:
      context: clang
    container_name: clang
    labels: [ 'devenv.type=clang' ]
    <<: *common-options

  # Clojure ---------------------------- {{{1
  clojure:
    image: clojure
    container_name: clojure
    command: bash
    labels: [ 'devenv.type=clojure' ]
    <<: *common-options

  clojure-repl:
    image: clojure
    container_name: clojure-repl
    labels: [ 'devenv.type=clojure-repl' ]
    <<: *common-options

  # Elixir ----------------------------- {{{1
  elixir:
    image: elixir
    container_name: elixir
    command: bash
    labels: [ 'devenv.type=elixir' ]
    <<: *common-options

  elixir-repl:
    image: elixir
    container_name: elixir-repl
    labels: [ 'devenv.type=elixir-repl' ]
    <<: *common-options

  # Erlang ----------------------------- {{{1
  erlang:
    image: erlang
    container_name: erlang
    command: bash
    labels: [ 'devenv.type=erlang' ]
    <<: *common-options

  erlang-repl:
    image: erlang
    container_name: erlang-repl
    labels: [ 'devenv.type=erlang-repl' ]
    <<: *common-options

  # FSharp ----------------------------- {{{1
  fsharp:
    image: fsharp
    container_name: fsharp
    command: bash
    labels: [ 'devenv.type=fsharp' ]
    <<: *common-options

  # GCC -------------------------------- {{{1
  gcc:
    image: gcc
    container_name: gcc
    command: bash
    labels: [ 'devenv.type=gcc' ]
    <<: *common-options

  # Golang ----------------------------- {{{1
  golang:
    image: golang
    container_name: golang
    command: bash
    labels: [ 'devenv.type=golang' ]
    <<: *common-options

  # Haskell ---------------------------- {{{1
  haskell:
    image: haskell
    container_name: haskell
    command: bash
    labels: [ 'devenv.type=haskell' ]
    <<: *common-options

  haskell-repl:
    image: haskell
    container_name: haskell-repl
    labels: [ 'devenv.type=haskell-repl' ]
    <<: *common-options

  # Julia ------------------------------ {{{1
  julia:
    image: julia
    container_name: julia
    command: bash
    labels: [ 'devenv.type=julia' ]
    <<: *common-options

  julia-repl:
    image: julia
    container_name: julia-repl
    labels: [ 'devenv.type=julia-repl' ]
    <<: *common-options

  # Mono ------------------------------- {{{1
  mono:
    image: mono
    container_name: mono
    command: bash
    labels: [ 'devenv.type=mono' ]
    <<: *common-options

  # Node ------------------------------- {{{1
  node:
    image: node
    container_name: node
    command: bash
    labels: [ 'devenv.type=node' ]
    <<: *common-options

  node-repl:
    image: node
    container_name: node-repl
    labels: [ 'devenv.type=node-repl' ]
    <<: *common-options

  # OpenJDK ---------------------------- {{{1
  openjdk:
    image: openjdk
    container_name: openjdk
    command: bash
    labels: [ 'devenv.type=openjdk' ]
    <<: *common-options

  openjdk-repl:
    image: openjdk
    container_name: openjdk-repl
    labels: [ 'devenv.type=openjdk-repl' ]
    <<: *common-options

  # Perl ------------------------------- {{{1
  perl:
    image: perl
    container_name: perl
    entrypoint: perl
    labels: [ 'devenv.type=perl' ]
    <<: *common-options

  perl-dbg:
    image: perl
    container_name: perl-dbg
    labels: [ 'devenv.type=perl-dbg' ]
    <<: *common-options

  perl-repl:
    image: local/perl-repl
    build:
      context: perl-repl
    container_name: perl-repl
    labels: [ 'devenv.type=perl-repl' ]
    <<: *common-options

  perl-shell:
    image: perl
    container_name: perl-shell
    command: bash
    labels: [ 'devenv.type=perl-shell' ]
    <<: *common-options

  # Perl6 ------------------------------ {{{1
  perl6:
    image: rakudo-star
    container_name: perl6
    entrypoint: perl6
    labels: [ 'devenv.type=perl6' ]
    <<: *common-options

  # TODO: check if there're REPL module in Perl6
  # TODO: update official name change: perl6 -> raku
  perl6-repl:
    image: rakudo-star
    container_name: perl6-repl
    labels: [ 'devenv.type=perl6-repl' ]
    <<: *common-options

  perl6-shell:
    image: rakudo-star
    container_name: perl6-shell
    command: bash
    labels: [ 'devenv.type=perl6-shell' ]
    <<: *common-options

  # Python ----------------------------- {{{1
  python:
    image: python
    container_name: python
    entrypoint: python
    labels: [ 'devenv.type=python' ]
    <<: *common-options

  python-repl:
    image: python
    container_name: python-repl
    labels: [ 'devenv.type=python-repl' ]
    <<: *common-options

  python-shell:
    image: python
    container_name: python-shell
    labels: [ 'devenv.type=python-shell' ]
    command: bash
    <<: *common-options

  # Ruby ------------------------------- {{{1
  ruby:
    image: ruby
    container_name: ruby
    entrypoint: ruby
    labels: [ 'devenv.type=ruby' ]
    <<: *common-options

  ruby-repl:
    image: ruby
    container_name: ruby-repl
    labels: [ 'devenv.type=ruby-repl' ]
    <<: *common-options

  ruby-shell:
    image: ruby
    container_name: ruby-shell
    command: bash
    labels: [ 'devenv.type=ruby-shell' ]
    <<: *common-options

  # Rust ------------------------------- {{{1
  rust:
    image: rust
    container_name: rust
    command: bash
    labels: [ 'devenv.type=rust' ]
    <<: *common-options

  # Doom-Emacs ------------------------- {{{1
  doom-emacs:
    image: local/doom-emacs
    build:
      context: doom-emacs
      args:
        HOST_UID: ${HOST_UID:-}
        HOST_GID: ${HOST_GID:-}
    container_name: doom-emacs
    labels: [ 'devenv.type=doom-emacs' ]
    environment:
      TERM: ${TERM:-xterm-256color}
    volumes:
      - ${HOME}/.doom.d:/home/linuxbrew/.doom.d
    <<: *common-options

  doom-emacs-x11:
    image: local/doom-emacs
    build:
      context: doom-emacs
      args:
        HOST_UID: ${HOST_UID:-}
        HOST_GID: ${HOST_GID:-}
    container_name: doom-emacs-x11
    labels: [ 'devenv.type=doom-emacs' ]
    environment:
      DISPLAY: ${DISPLAY:-:0}
      TERM: ${TERM:-xterm-256color}
    volumes:
      - ${HOME}/.doom.d:/home/linuxbrew/.doom.d
      - ${HOME}/.local/share/fonts:/usr/local/share/fonts
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    <<: *common-options

  # Spacemacs -------------------------- {{{1
  spacemacs:
    image: local/spacemacs
    build:
      context: spacemacs
      args:
        HOST_UID: ${HOST_UID:-}
        HOST_GID: ${HOST_GID:-}
    container_name: spacemacs
    labels: [ 'devenv.type=spacemacs' ]
    environment:
      TERM: ${TERM:-xterm-256color}
    volumes:
      - ${HOME}/.spacemacs.d:/home/linuxbrew/.spacemacs.d
    <<: *common-options

  spacemacs-x11:
    image: local/spacemacs
    build:
      context: spacemacs
      args:
        HOST_UID: ${HOST_UID:-}
        HOST_GID: ${HOST_GID:-}
    container_name: spacemacs-x11
    labels: [ 'devenv.type=spacemacs' ]
    environment:
      DISPLAY: ${DISPLAY:-:0}
      TERM: ${TERM:-xterm-256color}
    volumes:
      - ${HOME}/.spacemacs.d:/home/linuxbrew/.spacemacs.d
      - ${HOME}/.local/share/fonts:/usr/local/share/fonts
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    <<: *common-options

  # Spacevim --------------------------- {{{1
  spacevim:
    image: local/spacevim
    build:
      context: spacevim
      args:
        HOST_UID: ${HOST_UID:-}
        HOST_GID: ${HOST_GID:-}
    container_name: spacevim
    labels: [ 'devenv.type=spacevim' ]
    environment:
      TERM: ${TERM:-xterm-256color}
    volumes:
      - ${HOME}/.SpaceVim.d:/home/linuxbrew/.SpaceVim.d
    <<: *common-options

# vim: tabstop=2 shiftwidth=2 expandtab foldmethod=marker
